-- ============================================
-- TABLA DE TOPICS / ÁREAS DE INTERÉS
-- ============================================

CREATE TABLE public.topics (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  image text null,
  name text not null,
  name_es text null,
  description text null,
  description_es text null,
  "isActived" boolean not null default true,
  color text null default '#3b82f6'::text,
  icon text null,
  constraint topics_pkey primary key (id)
) TABLESPACE pg_default;

-- Crear índice para búsquedas
CREATE INDEX idx_topics_active ON public.topics("isActived") WHERE "isActived" = true;
CREATE INDEX idx_topics_name ON public.topics(name);

-- Habilitar RLS
ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;

-- Política para permitir lectura de topics activos a todos los usuarios autenticados
CREATE POLICY "Anyone can view active topics" ON public.topics
  FOR SELECT USING ("isActived" = true);

-- Política para que solo admins puedan modificar topics
CREATE POLICY "Only admins can modify topics" ON public.topics
  FOR ALL USING (auth.uid() IN (
    SELECT id FROM profiles WHERE role = 'admin'
  ));

-- ============================================
-- TABLA DE RELACIÓN: PROFILES_TOPICS
-- ============================================

CREATE TABLE public.profile_topics (
  id uuid not null default gen_random_uuid(),
  profile_id uuid not null,
  topic_id bigint not null,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint profile_topics_pkey primary key (id),
  constraint profile_topics_profile_fkey foreign KEY (profile_id) references profiles(id) on delete CASCADE,
  constraint profile_topics_topic_fkey foreign KEY (topic_id) references topics(id) on delete CASCADE,
  constraint unique_profile_topic unique (profile_id, topic_id)
) TABLESPACE pg_default;

-- Índices
CREATE INDEX idx_profile_topics_profile ON public.profile_topics(profile_id);
CREATE INDEX idx_profile_topics_topic ON public.profile_topics(topic_id);

-- Habilitar RLS
ALTER TABLE public.profile_topics ENABLE ROW LEVEL SECURITY;

-- Políticas
CREATE POLICY "Users can view own topic selections" ON public.profile_topics
  FOR SELECT USING (auth.uid() = profile_id);

CREATE POLICY "Users can insert own topic selections" ON public.profile_topics
  FOR INSERT WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Users can delete own topic selections" ON public.profile_topics
  FOR DELETE USING (auth.uid() = profile_id);

-- ============================================
-- DATOS DE EJEMPLO PARA TOPICS
-- ============================================

INSERT INTO public.topics (name, name_es, description, description_es, color, icon) VALUES
('Conservation Biology', 'Biología de la Conservación', 'Study of biodiversity and conservation efforts', 'Estudio de la biodiversidad y esfuerzos de conservación', '#10b981', 'leaf'),
('Ecology', 'Ecología', 'Study of organisms and their environment', 'Estudio de organismos y su entorno', '#22c55e', 'trees'),
('Genetics', 'Genética', 'Study of genes and heredity', 'Estudio de genes y herencia', '#a855f7', 'dna'),
('Evolution', 'Evolución', 'Study of evolutionary processes', 'Estudio de procesos evolutivos', '#f59e0b', 'git-branch'),
('Taxonomy', 'Taxonomía', 'Classification of organisms', 'Clasificación de organismos', '#6366f1', 'list-tree'),
('Climate Change', 'Cambio Climático', 'Study of climate change impacts', 'Estudio de impactos del cambio climático', '#ef4444', 'thermometer-sun'),
('Marine Biology', 'Biología Marina', 'Study of marine organisms', 'Estudio de organismos marinos', '#0ea5e9', 'waves'),
('Microbiology', 'Microbiología', 'Study of microorganisms', 'Estudio de microorganismos', '#ec4899', 'microscope'),
('Botany', 'Botánica', 'Study of plants', 'Estudio de plantas', '#22c55e', 'sprout'),
('Zoology', 'Zoología', 'Study of animals', 'Estudio de animales', '#f97316', 'paw-print'),
('Herpetology', 'Herpetología', 'Study of reptiles and amphibians', 'Estudio de reptiles y anfibios', '#84cc16', 'snake'),
('Ornithology', 'Ornitología', 'Study of birds', 'Estudio de aves', '#06b6d4', 'bird'),
('Entomology', 'Entomología', 'Study of insects', 'Estudio de insectos', '#eab308', 'bug'),
('Mycology', 'Micología', 'Study of fungi', 'Estudio de hongos', '#a16207', 'mushroom'),
('Biotechnology', 'Biotecnología', 'Application of biological systems and organisms', 'Aplicación de sistemas biológicos y organismos', '#3b82f6', 'flask-conical'),
('Ecotoxicology', 'Ecotoxicología', 'Study of toxic effects on ecosystems', 'Estudio de efectos tóxicos en ecosistemas', '#dc2626', 'skull'),
('Bioinformatics', 'Bioinformática', 'Application of computational methods to biology', 'Aplicación de métodos computacionales a la biología', '#8b5cf6', 'binary'),
('Population Biology', 'Biología Poblacional', 'Study of population dynamics', 'Estudio de dinámicas poblacionales', '#14b8a6', 'users'),
('Ecophysiology', 'Ecofisiología', 'Study of organism-environment interactions', 'Estudio de interacciones organismo-ambiente', '#f43f5e', 'activity'),
('Restoration Ecology', 'Ecología de la Restauración', 'Study of ecosystem restoration', 'Estudio de restauración de ecosistemas', '#10b981', 'refresh-cw');

